import { TitleComponent } from './title/title.component';

export const ATTRIBUTE = {
  // 'id': IdComponent,
  'title': TitleComponent,
  // 'type': TypeComponent,
  // 'width': WidthComponent,
  // 'height': HeightComponent,
  // 'placeholder': PlaceholderComponent,
  //   'border': BorderComponent,
  // 'fontFamily': FontFamilyComponent,
  // 'fontSize': FontSizeComponent,


  // 'allowSetStyle': AllowSetStyleComponent,
  // 'auto-height': AutoHeightComponent,
  // 'background': BackgroundComponent,
  // 'column': ColumnComponent,
  // 'countersign-attribute': CountersignAttributeComponent,
  // 'signature-picture-attribute': SignaturePictureAttributeComponent,
  // 'data-selector': DataSelectorComponent,
  // 'datasource': DatasourceComponent,
  // 'detail-layout': DetailLayoutComponent,
  // 'dynamic-info': DynamicInfoComponent,
  // 'editor': EditorComponent,
  // 'foreground': ForegroundComponent,
  // 'format': FormatComponent,
  // 'hide': HideComponent,
  // 'multiple': MultipleComponent,
  // 'option': OptionComponent,
  // 'orientation': OrientationComponent,
  // 'select-datasource': SelectDatasourceComponent,
  // 'select-option': SelectOptionComponent,
  // 'show-border': ShowBorderComponent,
  // 'show-name': ShowNameComponent,
  // 'upload': UploadComponent,
  // 'attachment-template': AttachmentTemplateComponent,
  // 'display-condition': DisplayConditionComponent,
  // 'link': LinkComponent,
  // 'default': DefaultComponent,
  // 'amount': AmountComponent,
  // 'barcode': BarcodeComponent
};
